#20200903
name: dcrclub_blog_build
on:
  push:
    branches: 
      - master
  schedule:
    - cron: 0 20 * * *
  release:
    types: [published]

jobs:

  build_openwrt:

    name: dcrclub_blog_build

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: 'Decred-CN/dcrclub.org'
          ref: master

      - name: Prepare Basic Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get update
          sudo -E apt-get -y install nodejs npm
          sudo npm install -g gitbook-cli

      - name: Compile gitbook
        run: |
          ls -alt
          sudo -E gitbook init
          sudo -E gitbook build
          
      - name: Prepare artifact
        run: |
          mkdir -p ./artifact/www
          mv _html ./artifact/www/

      - name: Deliver www
        uses: actions/upload-artifact@v2
        with:
          name: dcrclub_blog_www
          path: ./artifact/www/
